name: Automated Deployment for ODRS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ICTU-SERVER
    steps:
      - name: Checkout Code From Github
        uses: actions/checkout@v4

      - name: Copy Files tp Web Directory
        run: |
          xcopy /E /Y /I . "C:\Apache24\htdocs\BSP-ODRS"